name: deploy-mkdocs
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

# 赋予 GitHub Actions 推送代码到 gh-pages 分支的权限
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch-depth: 0 非常重要！
          # 因为你使用了 git-revision-date-localized 插件，必须拉取完整历史记录才能获取时间，否则打包会报错
          fetch-depth: 0
          
      - name: 配置 Git 用户信息
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    
      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
    
      - name: 设置缓存加快后续构建速度
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-mkdocs-material-${{ hashFiles('requirements.txt') }}
          path: .cache
          restore-keys: |
            ${{ runner.os }}-mkdocs-material-
    
      - name: 安装依赖包
        run: |
          # 如果你有 requirements.txt，优先使用它
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # 确保关键依赖被安装 (MkDocs, Material 主题，以及你使用的两个插件)
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-minify-plugin
    
      - name: 执行 MkDocs 编译并部署到 gh-pages 分支
        run: mkdocs gh-deploy --force
